spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: TeatroManager
  
  datasource:
    url: jdbc:postgresql://db:5432/teatroManager
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  # REMOVA ou COMENTE a seção spring.security.oauth2 se ela estiver assim:
  # security:
  #   oauth2:
  #     resourceserver:
  #       jwt: <--- O erro acontece aqui se estiver vazio ou mal formatado

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        # Removi o dialect conforme o aviso (WARN) do seu log
    open-in-view: false

jwt:
  secret: ${JWT_SECRET}

server:
  port: 5002